ARG ORG=dockcross
FROM ${ORG}/base:latest

ARG XCC_PREFIX=/usr/xcc

LABEL maintainer="Matt McCormick matt@mmmccormick.com"

# ADD arm-openwrt-linux-gnueabi.tar.gz ${XCC_PREFIX}

# This is for 32-bit ARMv7 Linux

# Crosstool-ng version 2024-05-21
ENV CT_VERSION=crosstool-ng-1.26.0

#include "common.crosstool"

# The cross-compiling emulator
RUN apt-get update \
&& apt-get install -y \
  qemu-user \
  qemu-user-static \
&& apt-get clean --yes

RUN curl -LO https://github.com/0xfe10/dynamic-actions/releases/download/v0.0.1-toolchain/arm-openwrt-linux-gnueabi.tar.gz \
  && mkdir -p ${XCC_PREFIX} \
  && tar -xzf arm-openwrt-linux-gnueabi.tar.gz -C ${XCC_PREFIX} \
  && rm -rf arm-openwrt-linux-gnueabi.tar.gz

# The CROSS_TRIPLE is a configured alias of the "arm-openwrt-linux-gnueabi" target.
ENV CROSS_TRIPLE=arm-openwrt-linux-gnueabi
ENV CROSS_ROOT=${XCC_PREFIX}/${CROSS_TRIPLE}
ENV AS=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-as \
    AR=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-ar \
    CC=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-gcc \
    CPP=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-cpp \
    CXX=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-g++ \
    LD=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-ld
    # FC=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-gfortran

ENV QEMU_LD_PREFIX="${CROSS_ROOT}/${CROSS_TRIPLE}/sysroot"
ENV QEMU_SET_ENV="LD_LIBRARY_PATH=${CROSS_ROOT}/lib:${QEMU_LD_PREFIX}"

ENV DEFAULT_DOCKCROSS_IMAGE=dockcross/linux-armv7a

COPY Toolchain.cmake ${CROSS_ROOT}/
ENV CMAKE_TOOLCHAIN_FILE=${CROSS_ROOT}/Toolchain.cmake

ENV PKG_CONFIG_PATH=/usr/lib/arm-openwrt-linux-gnueabi/

# Linux kernel cross compilation variables
ENV PATH=${PATH}:${CROSS_ROOT}/bin
ENV CROSS_COMPILE=${CROSS_TRIPLE}-
ENV ARCH=arm

#include "common.label-and-env"
