name: Build docker image

on:
#  push:
#    branches: [main]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        package:
          - name: ansible-playbook
          - name: deployment-trigger
            build-args: |
              KUSTOMIZE_VERSION=v5.4.3
              YQ_VERSION=v4.44.3
          - name: dockcross-openwrt-armv32-sunxi
            dockerfile: Dockerfile.in
            build-args: |
              XCC_PREFIX=/usr/xcc
          - name: kubernetes-manifests
            build-args: |
              KUBECTL_VERSION=1.30.5
              KUSTOMIZE_VERSION=v5.4.3
              HELM_VERSION=v3.15.3
              HELMFILE_VERSION=0.166.0-3.15.3
              # K8S_VERSION=1.21.2
              # HELMFILE_VERSION=v0.140.0
          - name: terraform-records
            build-args: |
              TERRAFORM_VERSION=1.9.6
              TERRAFORM_BACKEND_GIT_VERSION=v0.1.6
    steps:
      - uses: actions/checkout@v4
      - uses: benjlevesque/short-sha@v3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: ${{ matrix.package.name }}
        uses: docker/build-push-action@v6
        with:
          push: true
          context: docker-image/${{ matrix.package.name }}
          file: docker-image/${{ matrix.package.name }}/${{ matrix.package.dockerfile || 'Dockerfile' }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ matrix.package.name }}:sha-${{ env.SHA }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ matrix.package.name }}:latest
          build-args: ${{ matrix.package.build-args }}

